# Generated by Django 2.2.3 on 2019-08-16 02:02

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='product_img',
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(height_field=500, upload_to=products.models.changeName, width_field=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductDetail')),
            ],
        ),
    ]
