# Generated by Django 2.2.3 on 2019-08-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190816_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='img',
            field=models.ImageField(height_field=500, upload_to='productImg/', width_field=200),
        ),
    ]
