# Generated by Django 2.2.3 on 2019-08-22 15:03

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190817_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_for', models.CharField(max_length=10)),
                ('product_price', models.FloatField()),
                ('product_img', models.ImageField(upload_to=products.models.changeName)),
            ],
        ),
        migrations.RemoveField(
            model_name='productimg',
            name='product',
        ),
        migrations.AlterField(
            model_name='user_ordered_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_detail'),
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
        migrations.DeleteModel(
            name='ProductImg',
        ),
    ]
